name: advancepal
description: Frontend for Advance Pal, a trust based advance and debt tracking tool.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  rxdart: ^0.27.6

  advancepal_api:
    path: ./deps/advancepal_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
